name: ourbooks
version: 1.0.0+1
homepage: https://pub.dev
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
platforms:
  android:
  ios:
publish_to: none